# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Deep Inder Mohan
title: CS Ph.D. @ Georgia Tech
email: dmohan@gatech.edu


# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  deep-inder
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: deepindermohan.1
# flickr_username: jekyll
# instagram_username: that_deep_guy
linkedin_username: deep-inder-mohan-32173a154
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-9370-3060

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=P0g83jEAAAAJ&hl=en&oi=ao
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Deep Inder Mohan, and I'm a CS Ph.D. student at the [School of Cybersecurity and Privacy](https://scp.cc.gatech.edu/), located in the Georgia Institute of Technology.  My field of interest is <mark>Cryptography</mark>, including both Theoretical and Applied Cryptography. I am being advised at Georgia Tech by Professors [Sasha Boldyreva](https://faculty.cc.gatech.edu/~aboldyre/) and [Joseph Jaeger](https://faculty.cc.gatech.edu/~josephjaeger/)
  
  For more info, check out my [CV](documents/DeepInder_CV.pdf) 

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: |
          May the Force _Not_ Be with you: Brute-Force Resistant Biometric Authentication and Key Reconstruction


        link: https://eprint.iacr.org/2025/1211
        link_text: Paper Link
        quote: >
          Published in the proceedings of ACM CCS 2025;
          Co-authors: Alexandra Boldyreva, Tianxin Tang
        description: | # this will include new lines to allow paragraphs
          The use of biometric-based security protocols is on the steep rise. As biometrics become more popular, we witness more attacks. For example, recent BrutePrint/InfinityGauntlet attacks showed how to brute-force fingerprints stored on an Android phone in about 40 minutes. The attacks are possible because biometrics, like passwords, do not have high entropy. But unlike passwords, brute-force attacks are much more damaging for biometrics, because one cannot easily change biometrics in case of compromise. In this work, we propose a novel provably secure Brute-Force Resistant Biometrics (BFRB) protocol for biometric-based authentication and key reconstruction that protects against brute-force attacks even when the server storing biometric-related data is compromised. Our protocol utilizes a verifiable partially oblivious pseudorandom function, an authenticated encryption scheme, a pseudorandom function, and a hash. We formally define security for a BFRB protocol and reduce the security of our protocol to the security of the building blocks. We implement the protocol and study its performance for the ND-0405 iris dataset.

          
      - layout: top-middle
        title: |
          Generic and Algebraic Computation Models: When AGM Proofs Transfer to the GGM


        link: https://www.iacr.org/cryptodb/data/paper.php?pubkey=34299
        link_text: Paper Link
        quote: >
          Published in the proceedings of CRYPTO 2024;
          Co-author: Joseph Jaeger
        description: | # this will include new lines to allow paragraphs
          The Fuchsbauer, Kiltz, and Loss (Crypto 2018) claim that (some) hardness results in the algebraic group model imply the same hardness results in the generic group model was recently called into question by Katz, Zhang, and Zhou (Asiacrypt 2022). The latter gave an interpretation of the claim under which it is incorrect. We give an alternate interpretation under which it is correct, using natural frame- works for capturing generic and algebraic models for arbitrary algebraic structures. Most algebraic analyses in the literature can be captured by our frameworks, making the claim correct for them.

    
      - layout: top-middle
        title: Modeling Prejudice and Its Effect on Societal Prosperity
        link: https://www.tandfonline.com/doi/full/10.1080/17477778.2022.2039570
        link_text: Paper Link
        quote: >
          Published in the Taylor & Francis Journal of Simulation. Co-authors: Arjun Verma, Shrisha Rao
        description: | # this will include new lines to allow paragraphs
          Existing studies of the multi-group dynamics of prejudiced societies focus on the social-psychological knowledge behind the relevant processes. Instead, we create a multi-agent framework that simulates the propagation of prejudice and measures its tangible impact on prosperity. Our simulations show that even modeling prejudice as an exclusively out-group phenomenon nonetheless generates implicit in-group promotion, leading to higher relative prosperity of a prejudiced population. This model is a step towards a deeper understanding of the origins, propagation, and ramifications of prejudice through simulative studies grounded in apt theoretical backgrounds.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Brute-Force Resistant Biometric Cryptosystem
        # link: github.com/deep-guy/interviewQG
        # link_text: Project Website
        quote: >
         In collaboration with Sasha Boldyreva & Tianxin Tang
        description: | # this will include new lines to allow paragraphs
          Our objective is to create a biometrics-based key retrieval system that does not require users to remember any additional secrets beyond their biometrics, and yet achieves security against brute-force biometric attackers. 
        link: https://www.rsaconference.com/-/media/project/rsac/rsac-website/page-files/rsac-programs/security-scholar/security-scholar-posters/2024/security-scholar-poster---deep-inder-mohan---georgia-institute-of-technology-deep-inder-mohan.pdf?rev=ded5f7a08a3845768f501ccb9472c1e2&hash=5E3740366F8EC3118D7FEEAEAD3F739A
        link_text: Poster presented at RSA conference 2024

      - layout: top-middle
        title: Privacy Preserving Identification
        # link: github.com/deep-guy/interviewQG
        # link_text: Project Website
        quote: >
          Master's thesis @ IIITB under the supervision of Prof. Srinivas Vivek
        description: | # this will include new lines to allow paragraphs
          Foundational ID systems such as SSN and AADHAR can be critical to the effective governance of a nation. Since these systems deal with data that is inherently critical, securing this data becomes paramount. This poses a challenge to smaller nations, that do not have the resources to set up in-house servers to run these systems. In this project, we develop a Homomorphic Encryption based system that allows nations to levarage (potentially) untrusted third-party servers for storing and processing user data while ensuring that this data would remain secure - even if the third-party is breached. The accepted thesis can be found [here](documents/DeepInder-Thesis.pdf). This work was also presented by Prof. Srinivas Vivek in the Turing foundation's Trustworthy Digital Identity Conference held in London, U.K. on Sept. 16, 2022.
        link: https://arxiv.org/abs/2408.08002
        link_text: Manuscript available on arXiv
      


  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Georgia Institute of Technology
        caption: 2022 - present
        sub_title: Ph.D. in Computer Science
        # quote: >
        #   Established in 1999, IIITB, with its unique model of education, research, and industry interaction, has grown in stature to become an institution of considerable repute in academic as well as corporate circles. It is inspired by other renowned institutions, and also strives to emulate an academic culture that is on par with the best international institutions.
        # description: | # this will include new lines to allow paragraphs
        #   IIITB has taught me most of my key skills such as teamwork and working to tight deadlines. The varied faculty and strong research culture have allowed me to explore career options that simply wouldn't be possible in most other institutions.

      - layout: top-middle
        title: International Institute of Information Technology, Bangalore
        caption: 2017 - 2022
        sub_title: Integrated Masters in Computer Science
        # quote: >
        #   Established in 1999, IIITB, with its unique model of education, research, and industry interaction, has grown in stature to become an institution of considerable repute in academic as well as corporate circles. It is inspired by other renowned institutions, and also strives to emulate an academic culture that is on par with the best international institutions.
        # description: | # this will include new lines to allow paragraphs
        #   IIITB has taught me most of my key skills such as teamwork and working to tight deadlines. The varied faculty and strong research culture have allowed me to explore career options that simply wouldn't be possible in most other institutions.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Cryptography and Privacy research, I am also an avid debator. I have won multiple [competitions](https://twitter.com/iiitb_official/status/1100074139287777280) at the school and college level for debates and extempores, and have also served as the head of the Debate Society, IIIT Bangalore. 

      I also am a proficient MC, and have been the host for multiple events in IIITB, most notable of which is TEDxIIITBangalore, in 2018.
      
      [google](documents/google87d40fe7d3751a92.html)
      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
